import { Speaker } from './speakers.type'

export const speakerById: { [key: string]: Speaker } = {
  LegalLab: {
    id: 'LegalLab',
    name: 'Legal Lab',
    role: 'Colegio Jurisprudencia USFQ',
    image: '/images/allies/legal-lab.svg',
    linkedin: 'https://www.linkedin.com/showcase/usfq-jurisprudencia/',
  },
  DiegoJaramillo: {
    id: 'DiegoJaramillo',
    name: 'Diego Jaramillo',
    role: '',
    image: '/images/speakers/diego-jaramillo.jpg',
    linkedin: '',
  },
  FabianJaramillo: {
    id: 'FabianJaramillo',
    name: 'Fabián Jaramillo',
    role: '',
    image: '/images/speakers/fabian-jaramillo.jpg',
    linkedin: '',
  },
  JuanFranciscoGonzalez: {
    id: 'JuanFranciscoGonzalez',
    name: 'Juan Francisco González',
    role: '',
    image: '/images/speakers/juan-francisco-gonzalez.jpg',
    linkedin: '',
  },
  BarbaraTeran: {
    id: 'BarbaraTeran',
    name: 'Bárbara Terán',
    role: '',
    image: '/images/speakers/barbara-teran.jpg',
    linkedin: '',
  },
  JoseAdatty: {
    id: 'JoseAdatty',
    name: 'Jose Adatty',
    role: 'Abogado',
    image: '/images/speakers/jose-adatty.jpg',
    linkedin: 'https://www.linkedin.com/in/jos%C3%A9-adatty-229984205/',
  },
  PaulNoboa: {
    id: 'PaulNoboa',
    name: 'Paul Noboa',
    role: 'UCL | USFQ | Equity | LawyersEC | IIDF',
    image: '/images/speakers/paul-noboa.jpg',
    linkedin: 'https://www.linkedin.com/in/paulnoboavelasco/',
  },
  AndresSanchez: {
    id: 'AndresSanchez',
    name: 'Andrés Sánchez',
    role: '',
    // image: '/images/speakers/andres-sanchez.jpg',
    image: '/images/speakers/default.png',
    linkedin: '',
  },
  ChristianEspinoza: {
    id: 'ChristianEspinoza',
    name: 'Christian Espinoza',
    role: '',
    // image: '/images/speakers/christian-espinoza.jpg',
    image: '/images/speakers/default.png',
    linkedin: '',
  },
  FarithSimon: {
    id: 'FarithSimon',
    name: 'Farith Simon',
    role: '',
    // image: '/images/speakers/farith-simon.jpg',
    image: '/images/speakers/default.png',
    linkedin: '',
  },
  MiguelVillegas: {
    id: 'MiguelVillegas',
    name: 'Miguel Villegas',
    role: 'Lawyer | International Relations USFQ',
    image: '/images/speakers/miguel-villegas.jpg',
    linkedin: 'https://www.linkedin.com/in/miguel-%C3%A1ngel-villegas-4984b1199/',
  },
  JoseSebastianPonce: {
    id: 'JoseSebastianPonce',
    name: 'Jose Sebastián Ponce',
    role: '',
    image: '/images/speakers/jose-sebastian-ponce.jpg',
    linkedin: '',
  },
  NicolasSerrano: {
    id: 'NicolasSerrano',
    name: 'Nicolás Serrano',
    role: 'Blockchain Developer | Software Engineer',
    image: "/images/speakers/nicolas-serrano.png",
    linkedin: 'https://www.linkedin.com/in/nicoserranop/',
  },
  SantiagoLeon: {
    id: 'SantiagoLeon',
    name: 'Santiago León',
    role: 'Blockchain & Business Consultant',
    image: '/images/speakers/santiago-leon.jpg',
    linkedin: 'https://www.linkedin.com/in/santiagoleonpinzon/',
  },
  AlexPadilla: {
    id: 'AlexPadilla',
    name: 'Alex Padilla',
    role: 'Ethereum Tricolor | Software Engineering EPN',
    image: '/images/speakers/alex-padilla.png',
    linkedin: 'https://www.linkedin.com/in/hilmalex/',
  },
  // Tuesday
  FranciscoRamos: {
    id: 'FranciscoRamos',
    name: 'Francisco Ramos',
    role: 'Profesor e investigador School of Business USFQ',
    image: '/images/speakers/francisco-ramos.jpeg',
    linkedin: 'https://www.linkedin.com/in/francisco-ramos-1a319241/',
  },
  JoseDanielRubio: {
    id: 'JoseDanielRubio',
    name: 'Jose Daniel Rubio',
    role: 'Estudiante de Finanzas en la USFQ',
    image: '/images/speakers/jose-daniel-rubio.jpg',
    linkedin: 'https://www.linkedin.com/in/jos%C3%A9-daniel-rubio-0086921a5/',
  },
  FelipeSalgado: {
    id: 'FelipeSalgado',
    name: 'Felipe Salgado',
    role: 'Fundador Aura Dogs y generalista de blockchain',
    image: '/images/speakers/felipe-salgado.png',
    linkedin: 'https://www.linkedin.com/in/felipesalgadoramos/',
  },
  MauricioRubio: {
    id: 'MauricioRubio',
    name: 'Mauricio Rubio',
    role: 'Master y empresario en Blockchain y DeFi',
    image: "/images/speakers/mauricio-rubio.jpg",
    linkedin: 'https://www.linkedin.com/in/maurorubiot/',
  },
  ChristianNarvaez: {
    id: 'ChristianNarvaez',
    name: 'Christian Narváez',
    role: 'Founder of Rayo Capital | Co-Founder of Web3 Familia',
    image: '/images/speakers/christian-narvaez.jpg',
    linkedin: 'https://www.linkedin.com/in/narvaezchristian/',
  },
  LuisEspinosaGoded: {
    id: 'LuisEspinosaGoded',
    name: 'Luis Espinosa Goded',
    role: 'Profesor USFQ economía, Columnista en Primicias',
    image: '/images/speakers/luis-espinosa-goded.jpg',
    linkedin: 'https://www.linkedin.com/in/luis-espinosa-goded-1932657/',
  },
  // Wednesday
  PazGomez: {
    id: 'PazGomez',
    name: 'Paz Gómez',
    role: 'Profesor Asociado ITAM Mexico en Blockchain',
    image: '/images/speakers/paz-gomez.jpg',
    linkedin: 'https://www.linkedin.com/in/mpazgomezm',
  },
  JoseLuisBenitez: {
    id: 'JoseLuisBenitez',
    name: 'Jose Luis Benitez',
    role: 'Director | Co-founder Taqui Latam',
    image: '/images/speakers/jose-benitez.jpg',
    linkedin: 'https://www.linkedin.com/in/jos%C3%A9-benitez-23295b15',
  },
  FedericoAquino: {
    id: 'FedericoAquino',
    name: 'Federico Aquino',
    role: 'Ceo Taqqui Latam',
    image: '/images/speakers/federico-aquino.jpg',
    linkedin: 'https://www.linkedin.com/in/fedeaquino',
  },
  ClaudioCossio: {
    id: 'ClaudioCossio',
    name: 'Claudio Cossio',
    role: 'Cofundador de Meta Pool',
    image: '/images/speakers/claudio-cossio.jpg',
    linkedin: 'https://www.linkedin.com/in/ccossio/',
  },
  // Thursday
  LuisUshina: {
    id: 'LuisUshiña',
    name: 'Luis Fernando Ushiña',
    role: 'Web3, Ethereum & Blockchain Developer',
    image: '/images/speakers/luis-fernando-ushina.jpg',
    linkedin: 'https://www.linkedin.com/in/wolfcito/',
  },
  LuisCarchi: {
    id: 'LuisCarchi',
    name: 'Luis Carchi',
    role: '',
    image: '/images/speakers/luis-carchi.jpg',
    linkedin: 'Co-founder building web3 security',
  },
  IrwinTello: {
    id: 'IrwinTello',
    name: 'Irwin Tello',
    role: 'QuickNode Ambassador',
    image: '/images/speakers/irwin-tello.jpg',
  },
  ErrolCartwright: {
    id: 'ErrolCartwright',
    name: 'Errol Cartwright',
    role: '',
    image: '/images/speakers/default.png',
    linkedin: '',
  },
  Turco: {
    id: 'Turco',
    name: 'Turco',
    role: 'Aurora Community Leader',
    image: '/images/speakers/default.png',
  },
  // Friday
  JoseIgnacioNaranjo: {
    id: 'JoseNaranjo',
    name: 'José Ignacio Naranjo',
    role: 'Estudiante Ing. Software UDLA',
    // image: "/images/speakers/jose-naranjo.jpg",
    image: '/images/speakers/JN.jpg',
    linkedin: 'https://ec.linkedin.com/in/jose-ignacio-naranjo-martinez-30bb17272',
  },
  AltairBarahona: {
    id: 'AltairBarahona',
    name: 'Altair Barahona',
    role: 'Software Engineer',
    image: "/images/speakers/altair-barahona.jpg",
    linkedin: 'https://www.linkedin.com/in/altair-barahona/',
  },
  CrisInCrypto: {
    id: 'CrisInCrypto',
    name: 'Cris In Crypto',
    role: '',
    // image: '/images/speakers/cris-in-cripto.jpeg',
    image: '/images/speakers/default.png',
    linkedin: '',
  },
  Default: {
    id: 'Default',
    name: 'Default',
    role: '',
    // image: "/images/speakers/wilson-yandun.jpg",
    image: '/images/speakers/default.png',
    linkedin: '',
  },
}
