import { Speaker } from './speakers.type'

export const speakerById: { [key: string]: Speaker } = {
  LegalLab: {
    id: 'LegalLab',
    name: 'Legal Lab',
    role: 'Colegio Jurisprudencia USFQ',
    image: '/images/allies/legal-lab.svg',
    linkedin: 'https://www.linkedin.com/showcase/usfq-jurisprudencia/',
  },
  DiegoJaramillo: {
    id: 'DiegoJaramillo',
    name: 'Diego Jaramillo',
    role: '',
    image: '/images/speakers/diego-jaramillo.jpg',
    linkedin: '',
  },
  FabianJaramillo: {
    id: 'FabianJaramillo',
    name: 'Fabián Jaramillo',
    role: '',
    image: '/images/speakers/fabian-jaramillo.jpg',
    linkedin: '',
  },
  XavierAndrade: {
    id: 'XavierAndrade',
    name: 'Xavier Andrade',
    role: '',
    image: "/images/speakers/xavier-andrade.jpg",
    linkedin: '',
  },
  JuanFranciscoGonzalez: {
    id: 'JuanFranciscoGonzalez',
    name: 'Juan Francisco González',
    role: '',
    image: '/images/speakers/juan-francisco-gonzalez.jpg',
    linkedin: '',
  },
  FranciscoAlmeida: {
    id: 'FranciscoAlmeida',
    name: 'Francisco Almeida',
    role: '',
    // image: "/images/speakers/francisco-almeida.jpg",
    image: '/images/speakers/default.png',
    linkedin: 'https://www.linkedin.com/showcase/usfq-jurisprudencia/',
  },
  JoseAdatty: {
    id: 'JoseAdatty',
    name: 'Jose Adatty',
    role: '',
    image: '/images/speakers/jose-adatty.jpg',
    linkedin: 'https://www.linkedin.com/in/jos%C3%A9-adatty-229984205/',
  },
  BarbaraTeran: {
    id: 'BarbaraTeran',
    name: 'Bárbara Terán',
    role: '',
    image: '/images/speakers/barbara-teran.jpg',
    linkedin:
      'https://media.licdn.com/dms/image/D4E35AQFgFGSE1QQzIw/profile-framedphoto-shrink_800_800/0/1680206038456?e=1682395200&v=beta&t=aKTquGRdd7IaVJCP6nvdRcEO6x53Vc8-laWA5daR6jI',
  },
  FelipeOleas: {
    id: 'FelipeOleas',
    name: 'Felipe Oleas',
    role: '',
    image: '/images/speakers/felipe-oleas.jpg',
    linkedin: 'https://equity.ec/',
  },
  MiguelVillegas: {
    id: 'MiguelVillegas',
    name: 'Miguel Villegas',
    role: '',
    image: '/images/speakers/miguel-villegas.jpg',
    linkedin:
      'https://media.licdn.com/dms/image/D4E35AQFgFGSE1QQzIw/profile-framedphoto-shrink_800_800/0/1680206038456?e=1682395200&v=beta&t=aKTquGRdd7IaVJCP6nvdRcEO6x53Vc8-laWA5daR6jI',
  },
  PaulNoboa: {
    id: 'PaulNoboa',
    name: 'Paul Noboa',
    role: '',
    image: '/images/speakers/paul-noboa.jpg',
    linkedin: 'https://www.linkedin.com/in/paulnoboavelasco/',
  },
  JoseSebastianPonce: {
    id: 'JoseSebastianPonce',
    name: 'Jose Sebastián Ponce',
    role: '',
    image: '/images/speakers/jose-sebastian-ponce.jpg',
    linkedin: '',
  },
  NicolasSerrano: {
    id: 'NicolasSerrano',
    name: 'Nicolás Serrano',
    role: '',
    // image: "/images/speakers/nicolas-serrano.jpg",
    image: '/images/speakers/default.png',
    linkedin: 'https://www.linkedin.com/in/nicoserranop/',
  },
  SantiagoLeon: {
    id: 'SantiagoLeon',
    name: 'Santiago León',
    role: '',
    image: '/images/speakers/santiago-leon.jpg',
    linkedin: 'https://www.linkedin.com/in/santiagoleonpinzon/',
  },
  AlexPadilla: {
    id: 'AlexPadilla',
    name: 'Alex Padilla',
    role: '',
    image: '/images/speakers/alex-padilla.png',
    linkedin: 'https://www.linkedin.com/in/hilmalex/',
  },
  // Tuesday
  FranciscoRamos: {
    id: 'FranciscoRamos',
    name: 'Francisco Ramos',
    role: '',
    image: '/images/speakers/francisco-ramos.jpeg',
    linkedin: 'https://www.linkedin.com/in/francisco-ramos-1a319241/',
  },
  JoseDanielRubio: {
    id: 'JoseDanielRubio',
    name: 'Jose Daniel Rubio',
    role: '',
    image: '/images/speakers/jose-daniel-rubio.jpg',
    linkedin: 'https://www.linkedin.com/in/jos%C3%A9-daniel-rubio-0086921a5/',
  },
  FelipeSalgado: {
    id: 'FelipeSalgado',
    name: 'Felipe Salgado',
    role: '',
    image: '/images/speakers/felipe-salgado.jpg',
    linkedin: 'https://www.linkedin.com/in/felipesalgadoramos/',
  },
  MauricioRubio: {
    id: 'MauricioRubio',
    name: 'Mauricio Rubio',
    role: '',
    // image: "/images/speakers/mauricio-rubio.jpg",
    image: '/images/speakers/default.png',
    linkedin: 'https://www.linkedin.com/in/maurorubiot/',
  },
  // Wednesday
  PazGomez: {
    id: 'PazGomez',
    name: 'Paz Gómez',
    role: '',
    image: '/images/speakers/paz-gomez.jpg',
    linkedin: 'https://www.linkedin.com/in/mpazgomezm',
  },
  JoseLuisBenitez: {
    id: 'JoseLuisBenitez',
    name: 'Jose Luis Benitez',
    role: '',
    image: '/images/speakers/jose-benitez.jpg',
    linkedin: 'https://www.linkedin.com/in/jos%C3%A9-benitez-23295b15',
  },
  FedericoAquino: {
    id: 'FedericoAquino',
    name: 'Federico Aquino',
    role: '',
    image: '/images/speakers/federico-aquino.jpg',
    linkedin: 'https://www.linkedin.com/in/fedeaquino',
  },
  // Thursday
  LuisUshina: {
    id: 'LuisUshiña',
    name: 'Luis Fernando Ushiña',
    role: '',
    image: '/images/speakers/luis-fernando-ushina.jpg',
    linkedin: 'https://www.linkedin.com/in/wolfcito/',
  },
  VladimirLuna: {
    id: 'VladimirLuna',
    name: 'Vladimir Luna',
    role: '',
    image: '/images/speakers/vladimir-luna.jpg',
    linkedin: 'https://www.linkedin.com/in/vladimirlunapmp/',
  },
  // Friday
  JoseIgnacioNaranjo: {
    id: 'JoseNaranjo',
    name: 'José Ignacio Naranjo',
    role: '',
    // image: "/images/speakers/jose-naranjo.jpg",
    image: '/images/speakers/JN.jpg',
    linkedin:
      'https://ec.linkedin.com/in/jose-ignacio-naranjo-martinez-30bb17272',
  },
  AltairBarahona: {
    id: 'AltairBarahona',
    name: 'Altair Barahona',
    role: '',
    // image: "/images/speakers/altair-barahona.jpg",
    image: '/images/speakers/Altair.jpeg',
    linkedin: 'https://www.linkedin.com/in/altair-barahona/',
  },
  RommelDeLosRios: {
    id: 'RommelDeLosRios',
    name: 'Rommel De Los Rios',
    role: '',
    // image: "/images/speakers/rommel-de-los-rios.jpg",
    image: '/images/speakers/Rommel.jpeg',
    linkedin: '',
  },
  RicardoRuano: {
    id: 'RicardoRuano',
    name: 'Ricardo Ruano',
    role: '',
    // image: "/images/speakers/ricardo-ruano.jpg",
    image: '/images/speakers/default.png',
    linkedin: '',
  },
  WilsonYandun: {
    id: 'WilsonYandun',
    name: 'Wilson Yandún',
    role: '',
    // image: "/images/speakers/wilson-yandun.jpg",
    image: '/images/speakers/Wilson.jpeg',
    linkedin: '',
  },
  Default: {
    id: 'Default',
    name: 'Default',
    role: '',
    // image: "/images/speakers/wilson-yandun.jpg",
    image: '/images/speakers/default.png',
    linkedin: '',
  },
}
