import { Speaker } from "./speakers.type";

export const speakerById: { [key: string]: Speaker } = {
    LegalLab: {
        id: "LegalLab",
        name: "Legal Lab",
        role: "Colegio Jurisprudencia USFQ",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgTBLQxBXGMBFxoFD8AbiWXU3acRBlL4lizWdwV39eyHpSTdJP1nkm6lqmXInCPV7GUy8&usqp=CAU",
        linkedin: "https://www.linkedin.com/showcase/usfq-jurisprudencia/",
    },
    DiegoJaramillo: {
        id: "DiegoJaramillo",
        name: "Diego Jaramillo",
        role: "",
        image: "/images/speakers/diego-jaramillo.jpg",
        linkedin: "",
    },
    FabianJaramillo: {
        id: "FabianJaramillo",
        name: "Fabian Jaramillo",
        role: "",
        // image: "/images/speakers/fabian.jaramillo.jpg",
        image: "/images/speakers/default.png",
        linkedin: "",
    },
    XavierAndrade: {
        id: "XavierAndrade",
        name: "Xavier Andrade",
        role: "",
        // image: "/images/speakers/xavier-andrade.jpg",
        image: "/images/speakers/default.png",
        linkedin: "",
    },
    JuanFranciscoGonzalez: {
        id: "JuanFranciscoGonzalez",
        name: "Juan Francisco Gonzalez",
        role: "",
        image: "/images/speakers/juan-francisco-gonzalez.jpg",
        linkedin: "",
    },
    FranciscoAlmeida: {
        id: "FranciscoAlmeida",
        name: "Francisco Almeida",
        role: "",
        // image: "/images/speakers/francisco-almeida.jpg",
        image: "/images/speakers/default.png",
        linkedin: "https://www.linkedin.com/showcase/usfq-jurisprudencia/",
    },
    JoseAdatty: {
        id: "JoseAdatty",
        name: "Jose Adatty",
        role: "",
        image: "/images/speakers/jose-adatty.jpg",
        linkedin: "https://www.linkedin.com/in/jos%C3%A9-adatty-229984205/",
    },
    FelipeOleas: {
        id: "FelipeOleas",
        name: "Felipe Oleas",
        role: "",
        image: "/images/speakers/felipe-oleas.jpg",
        linkedin: "https://equity.ec/",
    },
    MiguelVillegas: {
        id: "MiguelVillegas",
        name: "Miguel Villegas",
        role: "",
        image: "/images/speakers/miguel-villegas.jpg",
        linkedin: "https://media.licdn.com/dms/image/D4E35AQFgFGSE1QQzIw/profile-framedphoto-shrink_800_800/0/1680206038456?e=1682395200&v=beta&t=aKTquGRdd7IaVJCP6nvdRcEO6x53Vc8-laWA5daR6jI",
    },
    JoseSebastianPonce: {
        id: "JoseSebastianPonce",
        name: "Jose Sebastian Ponce",
        role: "",
        image: "/images/speakers/jose-sebastian-ponce.jpg",
        linkedin: "",
    },
    NicolasSerrano: {
        id: "NicolasSerrano",
        name: "Nicolas Serrano",
        role: "",
        image: "/images/speakers/nicolas-serrano.jpg",
        linkedin: "https://www.linkedin.com/in/nicoserranop/",
    },
    SantiagoLeon: {
        id: "SantiagoLeon",
        name: "Santiago Leon",
        role: "",
        image: "/images/speakers/santiago-leon.jpg",
        linkedin: "https://www.linkedin.com/in/santiagoleonpinzon/",
    },
    AlexPadilla: {
        id: "AlexPadilla",
        name: "Alex Padilla",
        role: "",
        image: "/images/speakers/alex-padilla.jpg",
        linkedin: "https://www.linkedin.com/in/hilmalex/",
    },
    PazGomez: {
        id: "PazGomez",
        name: "Paz Gomez",
        role: "",
        image: "/images/speakers/paz-gomez.jpg",
        linkedin: "https://www.linkedin.com/in/mpazgomezm",
    },
    JoseLuisBenitez: {
        id: "JoseLuisBenitez",
        name: "Jose Luis Benitez",
        role: "",
        image: "/images/speakers/jose-benitez.jpg",
        linkedin: "https://www.linkedin.com/in/jos%C3%A9-benitez-23295b15",
    },
    FedericoAquino: {
        id: "FedericoAquino",
        name: "Federico Aquino",
        role: "",
        image: "/images/speakers/federico-aquino.jpg",
        linkedin: "https://www.linkedin.com/in/fedeaquino",
    },
    LuisUshina: {
        id: "LuisUshiña",
        name: "Luis Ushiña",
        role: "",
        image: "/images/speakers/luis-ushina.jpg",
        linkedin: "https://www.linkedin.com/in/wolfcito/",
    },
    VladimirLuna: {
        id: "VladimirLuna",
        name: "Vladimir Luna",
        role: "",
        image: "/images/speakers/vladimir-luna.jpg",
        linkedin: "https://www.linkedin.com/in/vladimirlunapmp/",
    },
    JoseNaranjo: {
        id: "JoseNaranjo",
        name: "Jose Naranjo",
        role: "",
        // image: "/images/speakers/jose-naranjo.jpg",
        image: "/images/speakers/default.png",
        linkedin: "https://www.linkedin.com/in/altair-barahona/",
    },
    AltairBarahona: {
        id: "AltairBarahona",
        name: "Altair Barahona",
        role: "",
        // image: "/images/speakers/altair-barahona.jpg",
        image: "/images/speakers/default.png",
        linkedin: "https://www.linkedin.com/in/altair-barahona/",
    },
    RommelDeLosRios: {
        id: "RommelDeLosRios",
        name: "Rommel De Los Rios",
        role: "",
        // image: "/images/speakers/rommel-de-los-rios.jpg",
        image: "/images/speakers/default.png",
        linkedin: "",
    },
    RicardoRuano: {
        id: "RicardoRuano",
        name: "Ricardo Ruano",
        role: "",
        // image: "/images/speakers/ricardo-ruano.jpg",
        image: "/images/speakers/default.png",
        linkedin: "",
    },
};

